from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class AutoCheckinBigGodAssets: 


	# Image Rule Assets
	# 圈子界面的一键登录/或在福利中心时点击领取奖励时若未登会出现改按钮，点击该按钮登录后需要重新点击领取奖励 
	I_LOGIN = RuleImage(roi_front=(360,1069,58,29), roi_back=(0,768,720,512), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/image_login.png")
	# 点击进入圈子 
	I_CIRCLE = RuleImage(roi_front=(44,1229,55,34), roi_back=(0,1101,176,179), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_circle.png")
	# 确认是否处于圈子界面 
	I_CIRCLE_CHECK = RuleImage(roi_front=(44,1221,53,51), roi_back=(0,1067,273,213), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_circle_check.png")
	# 圈子界面进入福利中心 
	I_WELFARE = RuleImage(roi_front=(87,185,45,27), roi_back=(0,0,249,243), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_welfare.png")
	# 福利中心浮窗领取领取奖励按钮（兼是否有浮窗检测按钮） 
	I_CLAIM = RuleImage(roi_front=(595,539,60,33), roi_back=(0,0,720,1280), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_claim.png")
	# 重新登录按钮，刚启动app可能会因为在其他设备登录过显示重新登录按钮 
	I_LOGIN_AGAIN = RuleImage(roi_front=(527,694,53,30), roi_back=(0,335,720,556), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_login_again.png")
	# 确认是否处于福利中心界面 
	I_CLAIM_S = RuleImage(roi_front=(348,51,60,39), roi_back=(0,0,719,262), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_claim_s.png")
	# 取消更新按钮 
	I_X = RuleImage(roi_front=(352,912,19,48), roi_back=(0,375,720,768), threshold=0.75, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_x.png")
	# 福利中心打开礼物浮窗按钮
	I_GIFT = RuleImage(roi_front=(582,126,39,41), roi_back=(0,0,719,262), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_gift.png")

	# ----------------------- 游戏内领取（大神福利中心，横屏 1280x720） -----------------------
	# 注：本段为手工维护（与 res/image.json 同步），勿全量重跑 assets_extract.py 覆盖
	# 庭院曜日牌「曜」字（石碑样式，默认庭院可见）；牌上首字随星期变化，只裁稳定部分
	I_GAME_BOARD_STELE = RuleImage(roi_front=(30,403,29,24), roi_back=(0,0,1280,720), threshold=0.75, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_board_stele.png")
	# 庭院曜日牌「曜」字（挂轴样式，部分皮肤需左移镜头才可见）
	I_GAME_BOARD_SCROLL = RuleImage(roi_front=(566,469,25,23), roi_back=(0,0,1280,720), threshold=0.75, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_board_scroll.png")
	# 日程面板左上角「日程」标签（确认面板已打开）
	I_GAME_RICHENG_TAG = RuleImage(roi_front=(174,124,43,70), roi_back=(140,90,120,140), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_richeng_tag.png")
	# 日程面板右侧「通知」灯笼（切到通知页）
	I_GAME_NOTICE_LANTERN = RuleImage(roi_front=(1090,486,43,70), roi_back=(1055,440,110,190), threshold=0.75, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_notice_lantern.png")
	# 通知页「大神福利中心」横幅文字
	I_GAME_DS_BANNER = RuleImage(roi_front=(660,310,185,42), roi_back=(220,130,840,470), threshold=0.75, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_ds_banner.png")
	# 「福利中心」弹窗标题（确认弹窗已打开）
	I_GAME_WELFARE_TITLE = RuleImage(roi_front=(485,100,270,48), roi_back=(440,75,360,110), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_welfare_title.png")
	# 「领奖」金色按钮（可领取状态），点击后到账并弹出获得奖励
	I_GAME_CLAIM_BTN = RuleImage(roi_front=(650,210,88,44), roi_back=(240,175,535,460), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_claim_btn.png")
	# 「已达成」红章（该条目奖励已到账）
	I_GAME_CLAIM_DONE = RuleImage(roi_front=(652,325,84,44), roi_back=(240,175,535,460), threshold=0.75, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_claim_done.png")
	# 「福利中心」弹窗右上角关闭X
	I_GAME_POPUP_CLOSE = RuleImage(roi_front=(1050,180,45,45), roi_back=(1020,150,110,110), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_popup_close.png")
	# 日程面板右上角关闭X
	I_GAME_PANEL_CLOSE = RuleImage(roi_front=(1120,50,50,60), roi_back=(1090,30,90,110), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/game_panel_close.png")


