from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CubWarAssets:


	# Image Rule Assets（为崽而战·八百八狸盛宴， cub_war 子库，参照 touch_fish 组织）
	# 庭院右侧为崽而战入口
	I_MAIN_GOTO_CUB_WAR = RuleImage(roi_front=(1169,442,92,78), roi_back=(1150,420,120,120), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_main_goto_cub_war.png")
	# 为崽而战活动主页标志
	I_CHECK_CUB_WAR_PAGE = RuleImage(roi_front=(476,18,318,82), roi_back=(460,10,350,95), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_cub_war_page.png")
	# 八百八狸盛宴入口横幅
	I_GOTO_FEAST = RuleImage(roi_front=(445,161,50,240), roi_back=(430,150,90,270), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_goto_feast.png")
	# 盛宴地图标志
	I_CHECK_FEAST_MAP = RuleImage(roi_front=(497,10,160,38), roi_back=(460,5,260,60), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_feast_map.png")
	# 八百八狸讨伐中横幅，点击进入挑战页
	I_GOTO_BOSS = RuleImage(roi_front=(594,374,154,88), roi_back=(520,350,280,130), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_goto_boss.png")
	# 首领战斗挑战页标志
	I_CHECK_CHALLENGE = RuleImage(roi_front=(590,12,158,32), roi_back=(560,5,220,60), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_challenge.png")
	# 退治按钮
	I_RETREAT_FIRE = RuleImage(roi_front=(1118,578,100,62), roi_back=(1090,540,180,110), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_retreat_fire.png")
	# 讨伐开启弹窗立即前往按钮
	I_GOTO_PUSH = RuleImage(roi_front=(840,462,150,50), roi_back=(700,420,400,140), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_goto_push.png")
	# 活动弹窗右上角关闭
	I_POPUP_CLOSE = RuleImage(roi_front=(1185,36,42,44), roi_back=(1150,20,130,175), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_popup_close.png")
	# 本寮分组弹窗标志
	I_CHECK_GROUP = RuleImage(roi_front=(583,283,126,142), roi_back=(520,240,240,240), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_group.png")


	# Ocr Rule Assets（为崽而战·八百八狸盛宴）
	# 本宴剩余倒计时
	O_FEAST_END_COUNTDOWN = RuleOcr(roi=(497,50,268,44), area=(497,50,268,44), mode="Full", method="Default", keyword="", name="feast_end_countdown")
	# 单次挑战消耗（按钮×N）
	O_RETREAT_COST = RuleOcr(roi=(1163,636,76,26), area=(1163,636,76,26), mode="Digit", method="Default", keyword="", name="retreat_cost")
	# 每日消耗上限已用/总量
	O_DAILY_LIMIT = RuleOcr(roi=(1151,678,102,30), area=(1151,678,102,30), mode="DigitCounter", method="Default", keyword="", name="daily_limit")
