from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CubWarAssets:


	# Image Rule Assets（为崽而战·八百八狸盛宴， cub_war 子库，参照 touch_fish 组织）
	# 庭院右侧为崽而战入口（印章本体，跨皮肤通用）
	I_MAIN_GOTO_CUB_WAR = RuleImage(roi_front=(1172,446,70,70), roi_back=(1100,380,180,200), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_main_goto_cub_war.png")
	# 为崽而战活动主页标志
	I_CHECK_CUB_WAR_PAGE = RuleImage(roi_front=(476,18,318,82), roi_back=(460,10,350,95), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_cub_war_page.png")
	# 八百八狸盛宴入口横幅
	I_GOTO_FEAST = RuleImage(roi_front=(445,161,50,240), roi_back=(430,150,90,270), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_goto_feast.png")
	# 盛宴地图标志
	I_CHECK_FEAST_MAP = RuleImage(roi_front=(530,10,123,35), roi_back=(530,10,123,35), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_feast_map.png")
	# 八百八狸讨伐中横幅，点击进入挑战页
	I_GOTO_BOSS = RuleImage(roi_front=(594,374,154,88), roi_back=(520,350,280,130), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_goto_boss.png")
	# 首领战斗挑战页标志
	I_CHECK_CHALLENGE = RuleImage(roi_front=(590,12,158,32), roi_back=(560,5,220,60), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_challenge.png")
	# 退治按钮
	I_RETREAT_FIRE = RuleImage(roi_front=(1118,578,100,62), roi_back=(1090,540,180,110), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_retreat_fire.png")
	# 讨伐开启弹窗立即前往按钮
	I_GOTO_PUSH = RuleImage(roi_front=(840,462,150,50), roi_back=(700,420,400,140), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_goto_push.png")
	# 活动弹窗右上角关闭
	I_POPUP_CLOSE = RuleImage(roi_front=(1185,36,42,44), roi_back=(1150,20,130,175), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_popup_close.png")
	# 本寮分组弹窗标志
	I_CHECK_GROUP = RuleImage(roi_front=(583,283,126,142), roi_back=(520,240,240,240), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_group.png")
	# 妖怪退治区域页标题
	I_CHECK_YOKAI = RuleImage(roi_front=(406,20,111,33), roi_back=(370,5,200,60), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_yokai.png")
	# 神社区域页标题
	I_CHECK_SHRINE = RuleImage(roi_front=(406,20,111,33), roi_back=(370,5,200,60), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_check_shrine.png")
	# 盛宴地图上的鸟居（神社区域入口）
	I_MAP_TORII = RuleImage(roi_front=(567,294,98,88), roi_back=(300,55,980,655), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_map_torii.png")
	# 地图上的鲸组单兵军队（正在攻打的妖怪退治）
	I_MAP_ARMY_BLUE1 = RuleImage(roi_front=(342,185,61,86), roi_back=(300,55,980,655), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_map_army_blue1.png")
	# 地图上的鲸组三人军队（正在攻打的妖怪退治）
	I_MAP_ARMY_BLUE3 = RuleImage(roi_front=(300,55,980,655), roi_back=(300,55,980,655), threshold=0.75, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_map_army_blue3.png")
	# 地图上的鸥组单兵军队（正在攻打的妖怪退治）
	I_MAP_ARMY_YELLOW1 = RuleImage(roi_front=(437,564,59,88), roi_back=(300,55,980,655), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_map_army_yellow1.png")
	# 地图上的鸥组三人军队（正在攻打的妖怪退治）
	I_MAP_ARMY_YELLOW3 = RuleImage(roi_front=(300,55,980,655), roi_back=(300,55,980,655), threshold=0.75, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_map_army_yellow3.png")
	# 奖券排名面板的本大人印章（标记本组所在行）
	I_GROUP_STAMP = RuleImage(roi_front=(140,115,140,150), roi_back=(140,115,140,150), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_group_stamp.png")
	# 鲸组组图标（蓝色）
	I_GROUP_WHALE = RuleImage(roi_front=(55,120,45,145), roi_back=(55,120,45,145), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_icon_whale.png")
	# 鸥组组图标（黄色）
	I_GROUP_GULL = RuleImage(roi_front=(55,120,45,145), roi_back=(55,120,45,145), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_icon_gull.png")
	# 鲨组组图标（红色）
	I_GROUP_SHARK = RuleImage(roi_front=(55,120,45,145), roi_back=(55,120,45,145), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_icon_shark.png")
	# 地图上的鲨组三人军队（正在攻打的妖怪退治）
	I_MAP_ARMY_RED3 = RuleImage(roi_front=(300,55,980,655), roi_back=(300,55,980,655), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_map_army_red3.png")
	# 地图上的鲨组单兵军队（正在攻打的妖怪退治）
	I_MAP_ARMY_RED1 = RuleImage(roi_front=(573,491,58,89), roi_back=(300,55,980,655), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_map_army_red1.png")
	# 首领退治按钮锁链（未开启状态）
	I_BOSS_LOCKED = RuleImage(roi_front=(1135,585,70,90), roi_back=(1080,540,200,170), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_boss_locked.png")
	# 盛宴地图右下角指南针（点击回到本组大部队所在位置）
	I_MAP_COMPASS = RuleImage(roi_front=(1189,646,35,38), roi_back=(1189,646,35,38), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_map_compass.png")
	# 区域攻打界面右下角式神录按钮（首领讨伐中接管时从这里进式神录换御魂）
	I_AREA_SHIKIGAMI = RuleImage(roi_front=(1026,556,66,88), roi_back=(1000,540,110,120), threshold=0.8, method="Template matching", file="./tasks/CubWar/cub_war/cub_war_area_shikigami.png")


	# Ocr Rule Assets（为崽而战·八百八狸盛宴）
	# 本宴剩余倒计时
	O_FEAST_END_COUNTDOWN = RuleOcr(roi=(497,50,268,44), area=(497,50,268,44), mode="Full", method="Default", keyword="", name="feast_end_countdown")
	# 单次挑战消耗（按钮×N）
	O_RETREAT_COST = RuleOcr(roi=(1163,636,76,26), area=(1163,636,76,26), mode="Digit", method="Default", keyword="", name="retreat_cost")
	# 每日消耗上限已用/总量
	O_DAILY_LIMIT = RuleOcr(roi=(1151,678,102,30), area=(1151,678,102,30), mode="DigitCounter", method="Default", keyword="", name="daily_limit")
	# 首领未开启倒计时（如 38时8分后开启）
	O_BOSS_LOCKED_COUNTDOWN = RuleOcr(roi=(1060,486,190,34), area=(1060,486,190,34), mode="Full", method="Default", keyword="", name="boss_locked_countdown")
